name: Email Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      # Runs your local action[cite: 1]
      - name: Run Send Email Action
        uses: ./.github/actions/send-email-action
        with:
          resend_api_key: ${{ secrets.RESEND_API_KEY }}
          to_email: 'ahmadkhairicg@gmail.com'
          subject: 'Custom Action Email'
